// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID            string
	Content       string
	MediaType     string
	MediaUrns     []byte
	ScheduledTime pgtype.Timestamptz
	Visibility    string
	AccountID     int32
	CreatedAt     pgtype.Timestamptz
}

type SocialAccount struct {
	ID               int32
	Username         string
	PlatformUsername string
	AccessToken      string
	RefreshToken     pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
