// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Platform struct {
	ID           int32
	PlatformName string
	ApiEndpoint  string
	CreatedAt    pgtype.Timestamptz
}

type SocialAccount struct {
	ID               int32
	Username         string
	PlatformID       int32
	PlatformUsername pgtype.Text
	AccessToken      string
	RefreshToken     pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
