// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (SocialAccount, error)
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeletePlatform(ctx context.Context, platformName string) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, arg GetAccountParams) (SocialAccount, error)
	GetPlatform(ctx context.Context, platformName string) (Platform, error)
	GetUser(ctx context.Context, username string) (User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
