// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (SocialAccount, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, arg DeleteAccountParams) error
	DeletePost(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, username string) (SocialAccount, error)
	GetPost(ctx context.Context, id string) (Post, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListPosts(ctx context.Context) ([]Post, error)
	ListPostsPaginated(ctx context.Context, arg ListPostsPaginatedParams) ([]Post, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
